
version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app
    ports:
      - 80:3000
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app
    command: bash -c "npm i && touch index.js"
volumes:
  dependencies: